!include configs/envs/arm_env.yaml

DEBUG: 0

MAX_STEPS: null

RESET:
  # Reset means set the environment to the initial state
  MAX_ACTIONS_PER_EPS: 1
  OBJ:
    # Resample means choose new objects
    RESAMPLE: 1
    USE_RANDOM_SAMPLE: 0
    RESAMPLE_N_EPISODES: 10
  POS:
    KEEP: 1
    KEEP_NUM: 10

SAVE:
  SAVE_SAMPLES: 0
  SAVE_PATH: '/home/josep/e/samples'
  SAVER_TYPE: 'SingleObjSaver'

OBSERVATION:
  # Choose between `depth` and `rgb`.
  TYPE: 'depth'

ACTION:
  # Choose between `IMAGE`(in image space) and `CUBOID`(in a 3D cuboid region).
  # TYPE: 'IMAGE'
  TYPE: '4DIM'

  # The `CUBOID` defines a cuboid region for the grasping center.
  CUBOID:
    LOW: [0.30, -0.50, 0.02]
    HIGH: [0.90, 0.50, 0.12]


SIM:
  ARM:
    CONFIG: null
    POSE: [[0, 0, 0], [0, 0, 0]]

  GROUND:
    PATH: 'sim/envs/arm_env/planes/plane.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  WALL:
    USE: 0
    PATH: 'sim/envs/arm_env/wall.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  TABLE:
      PATH: 'sim/envs/arm_env/tables/table_grasp.urdf'
      POSE: [[0.6, 0, -0.9], [0, 0, 0]]
      HEIGHT_RANGE: [0.9, 0.9]

  GRASPABLE:
    PATHS: [
          '/home/josep/code/python/rlcode/robovat/models/urdfs/wooden_cup1/*.urdf',
    ]
    POSE:
      X: [0, 0.15]
      Y: [-0.2, 0.2]
      Z: 0.2
      ROLL: [-3.14, 3.14]
      PITCH: [-1.57, 1.57]
      YAW: [-3.14, 3.14]
    REMOVE_AFTER_GRASP: 1
    SCALE: [1, 1]
    NUM: 1

  MAX_ACTION_STEPS: 4000
