#
# Robot parts.
#

# Joint indices of the limb.
LIMB_JOINT_NAMES: [
  'panda_joint1',
  'panda_joint2',
  'panda_joint3',
  'panda_joint4',
  'panda_joint5',
  'panda_joint6',
  'panda_joint7',
  ]

# Link name of the end effector, for computing IK.
END_EFFCTOR_NAME: 'panda_hand'

# Joint name of the left finger of the gripper.
L_FINGER_NAME: 'panda_finger_joint1'

# Joint name of the right finger of the gripper.
R_FINGER_NAME: 'panda_finger_joint2'

# Link name of the left finger tip of the gripper.
L_FINGER_TIP_NAME: 'panda_leftfinger'

# Link name of the right finger tip of the gripper.
R_FINGER_TIP_NAME: 'panda_rightfinger'

# Open the gripper when resetting the robot.
OPEN_GRIPPER_WHEN_RESET: false


#
# Control constants.
#

# Default maximum time (in seconds) for position control.
LIMB_TIMEOUT: 15.0


# Neutral and default initial joint position of the limb.
LIMB_NEUTRAL_POSITIONS: [
  0.,
  0.458,
  0.31,
  -2.24,
  -0.30,
  2.66,
  2.32,
  ]

# Maximum joint velocities of the limb.
LIMB_MAX_VELOCITIES: [
   2.1750,
   2.1750,
   2.1750,
   2.1750,
   2.6100,
   2.6100,
   2.6100,
]

# Default maximum joint velocity ratio, chosen from (0, 1].
# Set it to 1.0 for data collection, 0.3 for demo.
LIMB_MAX_VELOCITY_RATIO: 0.1

# Threshold (in rads) for each joint for position control.
LIMB_POSITION_THRESHOLD: 0.04 # 0.008726640

# Height of the limb (installed on the base) from the ground, for computing IK.
LIMB_HEIGHT: 0.9

# Step size of a gripper trajectory.
END_EFFECTOR_STEP: 0.001

# Motion planning package.
# MOTION_PLANNING: 'moveit'
MOTION_PLANNING: null


#
# URDF.
#

# Path to the URDF file of the arm(without base, with gripper).
ARM_URDF: 'robots/franka_panda/franka_panda_arm.urdf'

# Path to the URDF file of the base.
BASE_URDF: 'robots/franka_panda/franka_panda_base.urdf'

