!include configs/envs/arm_env.yaml

DEBUG: 0

MAX_STEPS: null

OBSERVATION:
  # Choose between `depth` and `point_cloud`.
  TYPE: 'depth'

ACTION:
  # Choose between `IMAGE`(in image space) and `CUBOID`(in a 3D cuboid region).
  TYPE: 'IMAGE'

  # The `CUBOID` defines a cuvoid region for the grasping center.
  CUBOID:
    LOW: [0.30, -0.50, 0.02]
    HIGH: [0.90, 0.50, 0.12]

ARM:
  # Move the arm out of the table.
  OFFSTAGE_POSITIONS: [0.98, 0.458, 0.31, -1.24, -0.30, 2.66, 2.32]

  # Move the arm above the table.
  OVERHEAD_POSITIONS: [-1.57, 0.458, 0.31, -2.24, -0.30, 2.66, 2.32]

  # Move the arm to ready pose.
  READY_POSITIONS: [0, 0.458, 0.31, -2.24, -0.30, 2.66, 2.32]

  # The safe height to move the gripper above the table.
  GRIPPER_SAFE_HEIGHT: 0.4

  # The distance from the the end effector to the center of finger tips.
  FINGER_TIP_OFFSET: 0.125

  # If move to the overhead position after grasping.
  MOVE_TO_OVERHEAD_AFTER_GRASP: 1
    

SIM:
  ARM:
    CONFIG: 'configs/robots/franka_panda_sim.yaml'
    ROBOT: 'franka_panda'
    POSE: [[0, 0, 0], [0, 0, 0]]
    ARM_NAME: 'franka_panda'

  GROUND:
    PATH: 'sim/envs/arm_env/planes/plane.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  WALL:
    USE: 0
    PATH: 'sim/envs/arm_env/wall.urdf'
    POSE: [[0, 0, -0.9], [0, 0, 0]]

  TABLE:
      PATH: 'sim/envs/arm_env/tables/table_grasp.urdf'
      POSE: [[0.6, 0, -0.9], [0, 0, 0]]
      HEIGHT_RANGE: [0.9, 0.9]
  
  BIN:
      PATH: 'sim/envs/arm_env/bins/container.urdf'
      POSE: [[0.25, -0.28, -0.07], [0, 0, 0]]

  GRASPABLE:
    PATHS: [
      # 'sim/ycb_svl/*/*/*.urdf',
      'sim/OBJECT_URDF/*/*/*/obj.urdf',
    ]
    POSE:
      X: [-0.15, 0.15]
      Y: [-0.15, 0.15]
      Z: 0.3
      ROLL: [-3.14, 3.14]
      PITCH: [-1.57, 1.57]
      YAW: [-3.14, 3.14]
    # SCALE: [0.8, 1.2]
    SCALE: [1.0, 1.0]
    USE_RANDOM_SAMPLE: 1
    RESAMPLE_N_EPISODES: 1

  MAX_ACTION_STEPS: 4000
